arch:
  - amd64
  - ppc64le
sudo: false
language: node_js
node_js:
  - '14'
  - '12'
  - '10'
  - '8'
  - '6'
  - '4'
  - '0.12'
  - '0.10'
matrix:
    allow_failures:
       - node_js: '4'
       - node_js: '0.12'
       - node_js: '0.10'
after_script:
  - npm run coveralls
